name: APP E2E test

on:
  push:
    branches: [ "main" ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    environment: portfolio-v2

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm run build
    - run: npm run e2e-test