name: APP E2E test

env:
  API_PORT: ${{ secrets.API_PORT }}
  APP_DB_NAME: ${{ secrets.APP_DB_NAME }}
  APP_HTTPS_HOSTNAME: ${{ secrets.APP_HTTPS_HOSTNAME }}
  DB_URI: ${{ secrets.DB_URI }}
  MAILSENDER_PASSWORD: ${{ secrets.MAILSENDER_PASSWORD }}
  MAILSENDER_USERID: ${{ secrets.MAILSENDER_USERID }}
  NOTIFICATION_EMAIL_TO: ${{ secrets.NOTIFICATION_EMAIL_TO }}
  VITE_API_PORT: ${{ secrets.VITE_API_PORT }}

on:
  push:
    branches: [ "main" ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    environment: portfolio-v2

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm run build
    - run: npm run e2e-test